from __future__ import annotations

import datetime as dt
import enum

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Enum,
    Float,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from bot.database.base import Base


# ---------------------------------------------------------------------------
# Moderation intelligence
# ---------------------------------------------------------------------------
class ReportStatus(str, enum.Enum):
    PENDING = "pending"
    AUTO_RESOLVED = "auto_resolved"  # dual review agreed, automated action taken
    ESCALATED = "escalated"  # low confidence or disagreement -> staff review required
    DISMISSED = "dismissed"


class RecommendedAction(str, enum.Enum):
    """The *only* actions the AI is ever allowed to recommend or auto-apply.

    There is deliberately no KICK/BAN/PERMISSION_CHANGE member here — those code paths do not
    exist anywhere in this codebase. See bot/moderation/action_guard.py.
    """

    NONE = "none"
    WARN = "warn"
    DELETE_MESSAGE = "delete_message"
    TIMEOUT = "timeout"
    ESCALATE = "escalate"


class ModerationReport(Base):
    """A report of a member's behavior, either user-submitted (!report) or system-generated
    (spam/raid heuristics)."""

    __tablename__ = "moderation_reports"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    guild_id: Mapped[int] = mapped_column(BigInteger, index=True)
    reported_user_id: Mapped[int] = mapped_column(BigInteger, index=True)
    # NULL reporter_id means the report was system-generated by a heuristic detector.
    reporter_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    channel_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    reported_message_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    reason: Mapped[str] = mapped_column(Text)
    source: Mapped[str] = mapped_column(String(50), default="user")  # "user" | "heuristic:spam" | ...
    status: Mapped[ReportStatus] = mapped_column(Enum(ReportStatus), default=ReportStatus.PENDING, index=True)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class ModerationAnalysis(Base):
    """The AI's analysis of a ModerationReport, including dual-review outcome."""

    __tablename__ = "moderation_analyses"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    report_id: Mapped[int] = mapped_column(Integer, index=True)
    risk_score: Mapped[float] = mapped_column(Float)
    confidence: Mapped[float] = mapped_column(Float)
    recommended_action: Mapped[RecommendedAction] = mapped_column(Enum(RecommendedAction))
    evidence_summary: Mapped[str] = mapped_column(Text)
    primary_model: Mapped[str] = mapped_column(String(150))
    secondary_model: Mapped[str | None] = mapped_column(String(150), nullable=True)
    agreement: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    action_taken: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class StaffEscalation(Base):
    """Anything the AI was not confident enough to resolve on its own, queued for a human."""

    __tablename__ = "staff_escalations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    guild_id: Mapped[int] = mapped_column(BigInteger, index=True)
    source: Mapped[str] = mapped_column(String(50))  # "support" | "moderation" | "investigation"
    related_report_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    related_investigation_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    summary: Mapped[str] = mapped_column(Text)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    resolved: Mapped[bool] = mapped_column(Boolean, default=False)
    resolved_by: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    resolved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


# ---------------------------------------------------------------------------
# Investigations (join issues, punishment lookups, etc.)
# ---------------------------------------------------------------------------
class Investigation(Base):
    """A record of an !investigate run, aggregating one or more pluggable tool findings."""

    __tablename__ = "investigations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    guild_id: Mapped[int] = mapped_column(BigInteger, index=True)
    requested_by: Mapped[int] = mapped_column(BigInteger)
    target_user_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    intent: Mapped[str] = mapped_column(String(50))
    question: Mapped[str] = mapped_column(Text)
    summary: Mapped[str] = mapped_column(Text)
    confidence: Mapped[float] = mapped_column(Float)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class InvestigationFinding(Base):
    """A single pluggable tool's finding within an Investigation."""

    __tablename__ = "investigation_findings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    investigation_id: Mapped[int] = mapped_column(Integer, index=True)
    tool_key: Mapped[str] = mapped_column(String(100))
    finding_text: Mapped[str] = mapped_column(Text)
    confidence: Mapped[float] = mapped_column(Float)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


# ---------------------------------------------------------------------------
# Reference data investigation tools read from (staff-maintained; no external API in this
# skeleton -- wire a real integration in here when one exists, see PHASE2_PHASE3.md)
# ---------------------------------------------------------------------------
class KnownIssue(Base):
    """A known server issue staff have logged (e.g. "EU servers down for maintenance")."""

    __tablename__ = "known_issues"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    guild_id: Mapped[int] = mapped_column(BigInteger, index=True)
    title: Mapped[str] = mapped_column(String(200))
    description: Mapped[str] = mapped_column(Text)
    is_resolved: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
    created_by: Mapped[int] = mapped_column(BigInteger)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    resolved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class LinkedAccount(Base):
    """A Discord <-> in-game account link, as recorded by staff/an external linking flow."""

    __tablename__ = "linked_accounts"
    __table_args__ = (UniqueConstraint("guild_id", "discord_user_id", name="uq_linked_accounts_guild_user"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    guild_id: Mapped[int] = mapped_column(BigInteger, index=True)
    discord_user_id: Mapped[int] = mapped_column(BigInteger, index=True)
    ingame_username: Mapped[str] = mapped_column(String(100))
    linked_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class WhitelistStatus(str, enum.Enum):
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"


class WhitelistEntry(Base):
    """Whitelist application/status for an in-game username."""

    __tablename__ = "whitelist_entries"
    __table_args__ = (UniqueConstraint("guild_id", "ingame_username", name="uq_whitelist_guild_username"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    guild_id: Mapped[int] = mapped_column(BigInteger, index=True)
    ingame_username: Mapped[str] = mapped_column(String(100))
    discord_user_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    status: Mapped[WhitelistStatus] = mapped_column(Enum(WhitelistStatus), default=WhitelistStatus.PENDING)
    updated_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), onupdate=func.now())
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
